/**
 * Self-contained HTML album export.
 *
 * Produces a single HTML document with inline CSS and no JavaScript.
 * Anyone can open it in a browser and read the full family tree: a
 * printable tree overview plus a page-like card for every person with
 * their dates, places, relationships, and notes.
 *
 * Photos stored as blob ids (from IndexedDB) are NOT embedded — only
 * data URLs (`data:image/...`) are included. For a full photo-embedded
 * export, photos need to be resolved to data URLs by the caller first.
 */

import type { DataState, Person, FamilyEvent } from "./types";
import {
  findBirthEvent,
  findDeathEvent,
  getChildren,
  getParents,
  getSpouses
} from "./relationships";
import { yearOf } from "./dates";
import { EVENT_META } from "./eventMeta";
import { computeTreeLayout, TREE_CONSTANTS } from "./treeLayout";
import { generateStory } from "./story";

const { NODE_W, NODE_H } = TREE_CONSTANTS;

export type AlbumOptions = {
  title?: string;
  /** Optional map of photoId → data URL for embedding blob photos */
  resolvedPhotos?: Map<string, string>;
};

export function exportHtmlAlbum(
  data: DataState,
  options: AlbumOptions = {}
): string {
  const title = options.title || "Family album";
  const photoMap = options.resolvedPhotos ?? new Map();

  const people = Object.values(data.people).sort((a, b) => {
    const ya = yearOf(findBirthEvent(data, a.id)?.date);
    const yb = yearOf(findBirthEvent(data, b.id)?.date);
    if (ya != null && yb != null) return ya - yb;
    if (ya != null) return -1;
    if (yb != null) return 1;
    return a.name.localeCompare(b.name);
  });

  const styles = albumStyles();
  const treeSvg = buildTreeSvg(data, photoMap);
  const cards = people
    .map((person) => buildPersonCard(data, person, photoMap))
    .join("\n");

  const peopleCount = people.length;
  const eventCount = Object.keys(data.events).length;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <style>${styles}</style>
</head>
<body>
  <header class="album-header">
    <h1>${escapeHtml(title)}</h1>
    <p class="album-summary">
      ${peopleCount} ${peopleCount === 1 ? "person" : "people"} ·
      ${eventCount} ${eventCount === 1 ? "event" : "events"} ·
      generated ${new Date().toLocaleDateString()}
    </p>
  </header>

  <section class="album-tree">
    <h2>Family tree</h2>
    <div class="tree-wrap">${treeSvg}</div>
  </section>

  <section class="album-people">
    <h2>People</h2>
    <div class="people-grid">
      ${cards}
    </div>
  </section>

  <footer class="album-footer">
    <p>Generated by FamiliaLens</p>
  </footer>
</body>
</html>`;
}

// ─── Tree SVG ───────────────────────────────────────

function buildTreeSvg(data: DataState, photoMap: Map<string, string>): string {
  const layout = computeTreeLayout(data);
  if (layout.nodes.length === 0) {
    return '<p class="empty-note">No tree to draw — add relationships first.</p>';
  }

  const pad = 40;
  const w = layout.bounds.maxX - layout.bounds.minX + pad * 2;
  const h = layout.bounds.maxY - layout.bounds.minY + pad * 2;
  const tx = -layout.bounds.minX + pad;
  const ty = -layout.bounds.minY + pad;

  const nodeById = new Map(layout.nodes.map((n) => [n.id, n]));

  // Edges
  const edges: string[] = [];
  for (const u of layout.units) {
    if (u.members.length !== 2) continue;
    const padding = 8;
    edges.push(
      `<rect x="${u.centerX - u.width / 2 - padding}" y="${u.y - NODE_H / 2 - padding}" width="${u.width + padding * 2}" height="${NODE_H + padding * 2}" rx="22" class="couple-bg" />`
    );
  }

  // Parent edges: consolidate couple parents to single path
  type Edge = { kind: "single" | "couple"; x1: number; y1: number; x2: number; y2: number };
  const parentEdges: Edge[] = [];
  const byChild = new Map<string, string[]>();
  for (const e of layout.edges) {
    if (e.type !== "parent") continue;
    if (!byChild.has(e.to)) byChild.set(e.to, []);
    byChild.get(e.to)!.push(e.from);
  }
  for (const [childId, parentIds] of byChild) {
    const child = nodeById.get(childId);
    if (!child) continue;
    if (parentIds.length === 2) {
      const a = nodeById.get(parentIds[0]);
      const b = nodeById.get(parentIds[1]);
      if (a && b && a.unitId === b.unitId) {
        parentEdges.push({
          kind: "couple",
          x1: (a.x + b.x) / 2,
          y1: a.y + NODE_H / 2,
          x2: child.x,
          y2: child.y - NODE_H / 2
        });
        continue;
      }
    }
    for (const pid of parentIds) {
      const parent = nodeById.get(pid);
      if (!parent) continue;
      parentEdges.push({
        kind: "single",
        x1: parent.x,
        y1: parent.y + NODE_H / 2,
        x2: child.x,
        y2: child.y - NODE_H / 2
      });
    }
  }

  for (const e of parentEdges) {
    const midY = (e.y1 + e.y2) / 2;
    const dir = e.x2 > e.x1 ? 1 : -1;
    const r = Math.min(14, Math.abs(e.y2 - e.y1) / 4, Math.abs(e.x2 - e.x1) / 2 || 14);
    let d: string;
    if (Math.abs(e.x1 - e.x2) < 1) {
      d = `M ${e.x1} ${e.y1} L ${e.x2} ${e.y2}`;
    } else {
      d = `M ${e.x1} ${e.y1} L ${e.x1} ${midY - r} Q ${e.x1} ${midY} ${e.x1 + dir * r} ${midY} L ${e.x2 - dir * r} ${midY} Q ${e.x2} ${midY} ${e.x2} ${midY + r} L ${e.x2} ${e.y2}`;
    }
    edges.push(`<path d="${d}" class="parent-edge" />`);
  }

  // Nodes
  const nodes: string[] = [];
  for (const n of layout.nodes) {
    const photoUrl = resolvePhoto(n.person.photo, photoMap);
    const dateLabel = formatLifespan(n.birthYear, n.deathYear);
    const genderClass = `gender-${n.person.gender}`;
    const x = n.x - NODE_W / 2;
    const y = n.y - NODE_H / 2;

    const avatar = photoUrl
      ? `<foreignObject x="${n.x - 24}" y="${n.y - NODE_H / 2 + 14}" width="48" height="48">
           <div class="node-photo-wrap" xmlns="http://www.w3.org/1999/xhtml">
             <img src="${escapeAttr(photoUrl)}" alt="" />
           </div>
         </foreignObject>`
      : `<circle cx="${n.x}" cy="${n.y - NODE_H / 2 + 38}" r="24" class="avatar ${genderClass}" />
         <text x="${n.x}" y="${n.y - NODE_H / 2 + 44}" text-anchor="middle" class="avatar-initials">${escapeHtml(initials(n.person.name))}</text>`;

    nodes.push(`
      <g class="node">
        <rect x="${x}" y="${y}" width="${NODE_W}" height="${NODE_H}" rx="16" class="node-rect" />
        <rect x="${x}" y="${y}" width="${NODE_W}" height="5" class="node-stripe ${genderClass}" />
        ${avatar}
        <text x="${n.x}" y="${y + 82}" text-anchor="middle" class="node-name">${escapeHtml(truncate(n.person.name, 22))}</text>
        <text x="${n.x}" y="${y + 99}" text-anchor="middle" class="node-dates">${escapeHtml(dateLabel || "—")}</text>
      </g>`);
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" class="album-tree-svg">
    <g transform="translate(${tx} ${ty})">
      ${edges.join("\n")}
      ${nodes.join("\n")}
    </g>
  </svg>`;
}

// ─── Person card ────────────────────────────────────

function buildPersonCard(
  data: DataState,
  person: Person,
  photoMap: Map<string, string>
): string {
  const birth = findBirthEvent(data, person.id);
  const death = findDeathEvent(data, person.id);
  const by = yearOf(birth?.date);
  const dy = yearOf(death?.date);

  const parents = getParents(data, person.id);
  const spouses = getSpouses(data, person.id);
  const children = getChildren(data, person.id);

  const allEvents = Object.values(data.events)
    .filter((e) => e.people.includes(person.id))
    .sort((a, b) => {
      const ka = a.date?.sortKey ?? Number.POSITIVE_INFINITY;
      const kb = b.date?.sortKey ?? Number.POSITIVE_INFINITY;
      return ka - kb;
    });

  const photoUrl = resolvePhoto(person.photo, photoMap);
  const genderClass = `gender-${person.gender}`;

  const avatarBlock = photoUrl
    ? `<img src="${escapeAttr(photoUrl)}" alt="" class="card-photo" />`
    : `<div class="card-avatar ${genderClass}">${escapeHtml(initials(person.name))}</div>`;

  const lifespanLabel = formatLifespan(by, dy);

  const relations: string[] = [];
  if (parents.length > 0) {
    relations.push(
      `<div class="relation-line"><strong>Parents:</strong> ${parents.map((p) => escapeHtml(p.name)).join(", ")}</div>`
    );
  }
  if (spouses.length > 0) {
    relations.push(
      `<div class="relation-line"><strong>${spouses.length === 1 ? "Spouse" : "Spouses"}:</strong> ${spouses.map((p) => escapeHtml(p.name)).join(", ")}</div>`
    );
  }
  if (children.length > 0) {
    relations.push(
      `<div class="relation-line"><strong>Children:</strong> ${children.map((p) => escapeHtml(p.name)).join(", ")}</div>`
    );
  }

  const eventsList = allEvents
    .map((ev) => {
      const meta = EVENT_META[ev.type];
      const dateStr = ev.date?.display ?? "—";
      const placeStr = ev.place?.name ?? "";
      return `<li class="event-item">
        <span class="event-dot" style="background:${escapeAttr(meta?.color ?? "#888")}"></span>
        <span class="event-label">${escapeHtml(meta?.label ?? ev.type)}</span>
        <span class="event-meta">${escapeHtml(dateStr)}${placeStr ? ` · ${escapeHtml(placeStr)}` : ""}</span>
      </li>`;
    })
    .join("");

  const notesBlock = person.notes
    ? `<div class="card-notes">${escapeHtml(person.notes)}</div>`
    : "";

  const story = generateStory(data, person.id);
  const storyBlock = story
    ? `<div class="card-story">${escapeHtml(story)}</div>`
    : "";

  return `<article class="person-card" id="person-${escapeAttr(person.id)}">
    <header class="card-header">
      ${avatarBlock}
      <div class="card-header-body">
        <h3>${escapeHtml(person.name || "Unnamed")}</h3>
        <div class="card-lifespan">${escapeHtml(lifespanLabel || "No dates")}</div>
      </div>
    </header>
    ${storyBlock}
    ${relations.length > 0 ? `<div class="card-relations">${relations.join("")}</div>` : ""}
    ${eventsList ? `<ul class="card-events">${eventsList}</ul>` : ""}
    ${notesBlock}
  </article>`;
}

// ─── Helpers ────────────────────────────────────────

function resolvePhoto(photo: string | undefined, map: Map<string, string>): string | null {
  if (!photo) return null;
  if (photo.startsWith("data:") || photo.startsWith("http")) return photo;
  return map.get(photo) ?? null;
}

function formatLifespan(b: number | null, d: number | null): string {
  if (b == null && d == null) return "";
  if (b != null && d != null) return `${b} – ${d}`;
  if (b != null) return `b. ${b}`;
  return `d. ${d}`;
}

function initials(name: string): string {
  const parts = name.trim().split(/\s+/);
  if (!parts[0]) return "?";
  if (parts.length === 1) return parts[0][0].toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + "…";
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttr(s: string): string {
  return escapeHtml(s);
}

// ─── Stylesheet ─────────────────────────────────────

function albumStyles(): string {
  return `
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: "Georgia", "Times New Roman", serif;
      color: #2a2520;
      background: #f7f3ec;
      padding: 40px 20px;
      line-height: 1.5;
    }
    .album-header {
      text-align: center;
      max-width: 800px;
      margin: 0 auto 40px;
      border-bottom: 1px solid rgba(120, 90, 60, 0.2);
      padding-bottom: 24px;
    }
    .album-header h1 {
      font-size: 2.4rem;
      margin: 0 0 8px;
      color: #c07a20;
      font-weight: 700;
      letter-spacing: -0.02em;
    }
    .album-summary {
      color: #7a6e62;
      font-size: 0.95rem;
      font-style: italic;
      margin: 0;
    }
    .album-tree {
      max-width: 1200px;
      margin: 0 auto 60px;
    }
    .album-tree h2, .album-people h2 {
      font-size: 1.1rem;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      color: #7a6e62;
      border-bottom: 1px solid rgba(120, 90, 60, 0.15);
      padding-bottom: 8px;
      margin-bottom: 24px;
    }
    .tree-wrap {
      overflow-x: auto;
      background: #fffdf8;
      border: 1px solid rgba(120, 90, 60, 0.12);
      border-radius: 12px;
      padding: 20px;
    }
    .album-tree-svg { display: block; width: 100%; height: auto; max-width: 100%; }
    .couple-bg {
      fill: rgba(192, 122, 32, 0.06);
      stroke: rgba(192, 122, 32, 0.25);
      stroke-width: 1.5;
      stroke-dasharray: 3 3;
    }
    .parent-edge {
      fill: none;
      stroke: rgba(120, 90, 60, 0.55);
      stroke-width: 2;
      stroke-linecap: round;
      stroke-linejoin: round;
    }
    .node-rect {
      fill: #fffdf8;
      stroke: rgba(120, 90, 60, 0.25);
      stroke-width: 1.2;
    }
    .node-stripe.gender-M { fill: #3a72c0; }
    .node-stripe.gender-F { fill: #c45878; }
    .node-stripe.gender-U { fill: #78858e; }
    .avatar.gender-M { fill: #3a72c0; }
    .avatar.gender-F { fill: #c45878; }
    .avatar.gender-U { fill: #78858e; }
    .avatar-initials {
      fill: white;
      font-family: "Helvetica", sans-serif;
      font-size: 16px;
      font-weight: 700;
    }
    .node-photo-wrap {
      width: 100%;
      height: 100%;
      border-radius: 50%;
      overflow: hidden;
      border: 2px solid #fffdf8;
    }
    .node-photo-wrap img { width: 100%; height: 100%; object-fit: cover; display: block; }
    .node-name {
      fill: #2a2520;
      font-family: "Helvetica", sans-serif;
      font-size: 14px;
      font-weight: 600;
    }
    .node-dates {
      fill: #7a6e62;
      font-family: "Courier New", monospace;
      font-size: 11px;
    }

    .album-people {
      max-width: 1200px;
      margin: 0 auto;
    }
    .people-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
      gap: 20px;
    }
    .person-card {
      background: #fffdf8;
      border: 1px solid rgba(120, 90, 60, 0.12);
      border-radius: 12px;
      padding: 18px;
      page-break-inside: avoid;
    }
    .card-header {
      display: flex;
      align-items: center;
      gap: 14px;
      margin-bottom: 12px;
    }
    .card-photo {
      width: 60px;
      height: 60px;
      border-radius: 50%;
      object-fit: cover;
      border: 2px solid #f7f3ec;
    }
    .card-avatar {
      width: 60px;
      height: 60px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: 700;
      font-size: 1.1rem;
      font-family: "Helvetica", sans-serif;
    }
    .card-avatar.gender-M { background: #3a72c0; }
    .card-avatar.gender-F { background: #c45878; }
    .card-avatar.gender-U { background: #78858e; }
    .card-header-body h3 {
      margin: 0 0 4px;
      font-size: 1.15rem;
      color: #2a2520;
    }
    .card-lifespan {
      font-family: "Courier New", monospace;
      font-size: 0.82rem;
      color: #7a6e62;
    }
    .card-story {
      font-size: 0.92rem;
      color: #3a342e;
      line-height: 1.65;
      margin-bottom: 12px;
      padding: 12px 14px;
      background: rgba(255, 250, 240, 0.6);
      border-left: 3px solid rgba(192, 122, 32, 0.25);
      border-radius: 4px;
      font-style: italic;
    }
    .card-relations {
      font-size: 0.88rem;
      color: #4a443c;
      margin-bottom: 10px;
      padding: 10px 12px;
      background: rgba(192, 122, 32, 0.04);
      border-left: 3px solid rgba(192, 122, 32, 0.3);
      border-radius: 4px;
    }
    .relation-line { margin: 3px 0; }
    .relation-line strong { color: #7a6e62; }
    .card-events {
      list-style: none;
      margin: 0;
      padding: 0;
      border-top: 1px solid rgba(120, 90, 60, 0.1);
      padding-top: 10px;
    }
    .event-item {
      display: flex;
      align-items: baseline;
      gap: 8px;
      padding: 4px 0;
      font-size: 0.85rem;
    }
    .event-dot {
      display: inline-block;
      width: 8px;
      height: 8px;
      border-radius: 50%;
      flex-shrink: 0;
    }
    .event-label { font-weight: 600; color: #2a2520; min-width: 90px; }
    .event-meta { color: #7a6e62; font-family: "Courier New", monospace; font-size: 0.78rem; }
    .card-notes {
      margin-top: 12px;
      padding-top: 10px;
      border-top: 1px solid rgba(120, 90, 60, 0.1);
      font-size: 0.88rem;
      color: #4a443c;
      font-style: italic;
      white-space: pre-wrap;
    }
    .album-footer {
      text-align: center;
      max-width: 800px;
      margin: 40px auto 0;
      padding-top: 20px;
      border-top: 1px solid rgba(120, 90, 60, 0.15);
      color: #a89a8c;
      font-size: 0.78rem;
    }
    .empty-note {
      text-align: center;
      color: #a89a8c;
      font-style: italic;
      padding: 40px;
    }

    @media print {
      body { background: white; padding: 0; }
      .tree-wrap { border: none; padding: 10px; }
      .person-card { break-inside: avoid; }
    }
  `;
}
